[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh -c \"cd /app/backend && node main.js & nginx -g 'daemon off;'\""
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"